version: "2.1"

services:
  tommy-client:
    image: tommy-client
    build:
      context: ./run-docker
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200