version: "2.1"

services:
  tommy-client:
    image: tommy-client
    build: 
      context: ../tommy-client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  lehava-api-mock:
    image: lehava-api-mock
    container_name: lehava-api-mock
    build:
      context: ../lehava-api-mock
      dockerfile: Dockerfile
    ports:
      - 8050:8050

  tommy-server:
    image: tommy-server
    container_name: tommy-server
    build:
      context: ../tommy-server
      dockerfile: Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: production
      AUTH_CALLBACK_URL: /auth/callback
      PORT: 80
      SHRAGA_URL: http://13.79.7.3
      CLIENT_URL: http://tommy-client:4200
      REDIS_URL: 'redis://redis:6379'
    ports:
      - 80:80
    depends_on:
      - tommy-client
      - redis
  
  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    ports:
      - '6379:6379'