version: "3"

services:
  tommy-client:
    image: tommy-client
    build: 
      context: ../tommy-client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  lehava-api-mock:
    image: lehava-api-mock
    container_name: lehava-api-mock
    build:
      context: ../lehava-api-mock
      dockerfile: Dockerfile
    ports:
      - 8050:8050

  tommy-server:
    image: tommy-server
    container_name: tommy-server
    build:
      context: ../tommy-server
      dockerfile: Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: production
      AUTH_CALLBACK_URL: /auth/callback
      PORT: 80
      SHRAGA_URL: http://13.79.7.3
      CLIENT_URL: http://tommy-client:4200
      REDIS_URL: 'redis://redis:6379'
      RABBITMQ_URL: "amqp://rabbitmq:5672"
    ports:
      - 80:80
    depends_on:
      - tommy-client
      - redis
  
  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  access-token-service:
    image: "access-token-service"
    container_name: "access-token-service"
    build:
      context: ../access-token-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      RABBITMQ_URL: "amqp://rabbitmq:5672"
      REDIS_URL: 'redis://redis:6379'
    restart: on-failure
    depends_on:
      - redis
      - rabbitmq