filebeat.inputs:
  - type: container
    paths: 
      - '/var/lib/docker/containers/*/*.log'
    # json.message_key: log
    # json.keys_under_root: true
    fields:
      service: docker
  - type: log
    paths:
      - '/usr/share/filebeat/tommy/logs/*.log'
  
processors:
# - add_docker_metadata:
#     host: "unix:///var/run/docker.sock"
    
# - decode_json_fields:
#     fields: ["message"]
#     target: "json"
#     overwrite_keys: true

# output.elasticsearch:
#     hosts: ["elasticsearch:9200"]
#     indices:
#     - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

output.logstash:
  hosts: ["logstash"]

# logging.json: true
# logging.metrics.enabled: false