version: "2.1"

services:
  tommy-client:
    image: tommy-client
    build: 
      context: ../tommy-client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  tommy-server:
    image: tommy-server
    container_name: tommy-server
    build:
      context: ../tommy-server
      dockerfile: Dockerfile
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: production
      AUTH_CALLBACK_URL: /auth/callback
      PORT: 80
      SHRAGA_URL: http://shraga.prod.services.idf
      CLIENT_URL: http://tommy-client:4200
      REDIS_URL: 'redis://redis:6379'
      LEHAVA_API_HOST: "lehava-api-mock"
      LEHAVA_API_PORT: "8050"
    ports:
      - 80:80
    depends_on:
      - tommy-client
      - redis
  
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  rabbitmq:
    container_name: 'rabbitmq'
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  access-token-service:
    image: "access-token-service"
    container_name: "access-token-service"
    build:
      context: ../access-token-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      RABBITMQ_URL: "amqp://rabbitmq:5672"
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: 'nginx:alpine'